CREATE DATABASE ESTUDO_DE_CASO_II;
USE ESTUDOS_DE_CASO_II;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_TELEFONE VARCHAR(15) NOT NULL, 
PASS_EMAIL VARCHAR(70) NOT NULL,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_RUA VARCHAR(50) NOT NULL,
PASS_NUMRUA INT NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_ESTADO VARCHAR(20) NOT NULL,
PASS_CEP VARCHAR(10) NOT NULL,
PASS_PAÍS VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM VARCHAR(50) NOT NULL,
VOO_AEROP_DESTINO VARCHAR(50) NOT NULL,
VOO_AERONAVE TEXT NOT NULL); 

CREATE TABLE IF NOT EXISTS RESERVAS(
RESER_COD INT PRIMARY KEY,
CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(RESER_PASS) REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT FK_VOOS FOREIGN KEY(RESER_VOO) REFERENCES VOOS(VOO_ID));

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(100) NOT NULL,
FUNC_DATANASC TEXT NOT NULL,
FUNC_CPF INT NOT NULL,
FUNC_FUNÇÃO VARCHAR(50) NOT NULL,
FUNC_RUA VARCHAR(50) NOT NULL,
FUNC_NUMRUA INT NOT NULL,
FUNC_BAIRRO VARCHAR(35) NOT NULL,
FUNC_CEP VARCHAR(10) NOT NULL,
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_ESTADO VARCHAR(50) NOT NULL,
FUNC_PAIS VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS OPERAÇÃO_VOO(
FV_FUNCIONARIOS INT,
FV_VOOS INT,
PRIMARY KEY(FV_FUNCIONARIOS,FV_VOOS),
CONSTRAINT FV_FK_FUNCIONARIOS FOREIGN KEY(FV_FUNCIONARIOS) REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT FV_FK_VOOS FOREIGN KEY(FV_VOOS) REFERENCES VOOS(VOO_ID));

CREATE TABLE IF NOT EXISTS AERONAVES(
AERON_PREFIXO VARCHAR(10) PRIMARY KEY,
AERON_MODELO VARCHAR(30) NOT NULL,
AERON_ANOFABR DATE NOT NULL,
AERON_AUTONOMIA TEXT NOT NULL,
AERON_CAPACIDADE INT NOT NULL,
AERON_FABRICANTE VARCHAR(30) NOT NULL);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_CODIGO INT PRIMARY KEY,
AEROP_NOME VARCHAR(50) NOT NULL,
AEROP_CIDADE VARCHAR(50) NOT NULL,
AEROP_PAIS VARHCAR(50) NOT NULL,
AEROP_LATITUDE INT NOT NULL,
AEROP_LONGITUDE INT NOT NULL);






