CREATE DATABASE ESTUDO_DE_CASO_II;
USE ESTUDOS_DE_CASO_II;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_TELEFONE VARCHAR(15) NOT NULL, 
PASS_EMAIL VARCHAR(70) NOT NULL,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_RUA VARCHAR(50) NOT NULL,
PASS_NUMRUA INT NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_ESTADO VARCHAR(20) NOT NULL,
PASS_CEP VARCHAR(10) NOT NULL,
PASS_PAÍS VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM VARCHAR(50) NOT NULL,
VOO_AEROP_DESTINO VARCHAR(50) NOT NULL,
VOO_AERONAVE TEXT NOT NULL); 

CREATE TABLE IF NOT EXISTS RESERVAS(
RESER_COD INT PRIMARY KEY,
CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(RESER_PASS) REFERENCES PASSAGEIROS(PASS_CPF)
CONSTRAINT FK_VOOS FOREIGN KEY(RESER_VOO) REFERENCES VOOS(VOO_ID));


